// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUniswapV2RouterLike$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUniswapV2RouterLike";
  readonly sourceName: "contracts/V2SwapLib.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"amountIn","type":"uint256"},{"internalType":"uint256","name":"amountOutMin","type":"uint256"},{"internalType":"address[]","name":"path","type":"address[]"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"}],"name":"swapExactTokensForTokens","outputs":[{"internalType":"uint256[]","name":"amounts","type":"uint256[]"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/V2SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

export interface V2SwapLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "V2SwapLib";
  readonly sourceName: "contracts/V2SwapLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212202c23603d56668edb50c14dcc098db3621363594108212459bf484e318fd907d564736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212202c23603d56668edb50c14dcc098db3621363594108212459bf484e318fd907d564736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/V2SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniswapV2RouterLike"]: IUniswapV2RouterLike$Type
    ["V2SwapLib"]: V2SwapLib$Type;
    ["contracts/V2SwapLib.sol:IUniswapV2RouterLike"]: IUniswapV2RouterLike$Type
    ["contracts/V2SwapLib.sol:V2SwapLib"]: V2SwapLib$Type;
  }
}