// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ArbQuoterConfigLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ArbQuoterConfigLib";
  readonly sourceName: "contracts/ArbQuoterConfigLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220c33a591b1e1751bb7fc5b9f17bb1bcbe7de1adb9f601a8fb696a5bf03095ef7d64736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220c33a591b1e1751bb7fc5b9f17bb1bcbe7de1adb9f601a8fb696a5bf03095ef7d64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ArbQuoterConfigLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ArbQuoterConfigLib"]: ArbQuoterConfigLib$Type;
    ["contracts/ArbQuoterConfigLib.sol:ArbQuoterConfigLib"]: ArbQuoterConfigLib$Type;
  }
}