// pairsSushiV2.stabs.ts
import {
  ADOGE,
  ARB,
  ARBY,
  ARVAULT,
  DAI,
  DPX,
  EMAX,
  FLUID,
  FLUX,
  GMX,
  GOHM,
  HASH,
  HWT,
  JETH,
  LINK,
  LIQD,
  MAGIC,
  MIM,
  OMNI,
  PEPE,
  SHARBI, // если у тебя токен назывался $SHARBI — используй SHARBI (без $) в tokens.stabs
  SPELL,
  SUSHI,
  USDC,
  USDCE,
  USDT,
  WBTC,
  WETH,
} from "../../tokens.stabs";

import {
  POOL_SUSHI_V2_WETH_HASH_03,
  POOL_SUSHI_V2_WETH_USDCE_03,
  POOL_SUSHI_V2_WETH_MAGIC_03,
  POOL_SUSHI_V2_WETH_DPX_03,
  POOL_SUSHI_V2_WETH_ARVAULT_03,
  POOL_SUSHI_V2_WETH_SPELL_03,
  POOL_SUSHI_V2_WETH_ARBY_03,
  POOL_SUSHI_V2_WETH_USDT_03,
  POOL_SUSHI_V2_WETH_WBTC_03,
  POOL_SUSHI_V2_WETH_ADOGE_03,
  POOL_SUSHI_V2_WETH_LIQD_03,
  POOL_SUSHI_V2_WETH_MIM_03,
  POOL_SUSHI_V2_WETH_FLUID_03,
  POOL_SUSHI_V2_WETH_EMAX_03,
  POOL_SUSHI_V2_WETH_USDC_03,
  POOL_SUSHI_V2_WETH_JETH_03,
  POOL_SUSHI_V2_WETH_SUSHI_03,
  POOL_SUSHI_V2_WETH_PEPE_03,
  POOL_SUSHI_V2_WETH_FLUX_03,
  POOL_SUSHI_V2_WETH_OMNI_03,
  POOL_SUSHI_V2_WETH_HWT_03,
  POOL_SUSHI_V2_WETH_GOHM_03,
  POOL_SUSHI_V2_WETH_SHARBI_03,
  POOL_SUSHI_V2_WETH_LINK_03,
  POOL_SUSHI_V2_WETH_ARB_03,
  POOL_SUSHI_V2_WETH_DAI_03,
  POOL_SUSHI_V2_WETH_GMX_03,
} from "./poolsSushiV2.stabs";
import {IPair} from '../../../state.types';

// ======================================================================
// PAIRS
// ======================================================================

// ==================== PAIR: WETH → X (SUSHI V2) ====================

export const PAIR_SUSHI_V2_WETH_HASH_3000_WETH_TO_HASH: IPair = { ...POOL_SUSHI_V2_WETH_HASH_03, tokenIn: WETH, tokenOut: HASH };
export const PAIR_SUSHI_V2_WETH_USDCE_3000_WETH_TO_USDCE: IPair = { ...POOL_SUSHI_V2_WETH_USDCE_03, tokenIn: WETH, tokenOut: USDCE };
export const PAIR_SUSHI_V2_WETH_MAGIC_3000_WETH_TO_MAGIC: IPair = { ...POOL_SUSHI_V2_WETH_MAGIC_03, tokenIn: WETH, tokenOut: MAGIC };
export const PAIR_SUSHI_V2_WETH_DPX_3000_WETH_TO_DPX: IPair = { ...POOL_SUSHI_V2_WETH_DPX_03, tokenIn: WETH, tokenOut: DPX };
export const PAIR_SUSHI_V2_WETH_ARVAULT_3000_WETH_TO_ARVAULT: IPair = { ...POOL_SUSHI_V2_WETH_ARVAULT_03, tokenIn: WETH, tokenOut: ARVAULT };
export const PAIR_SUSHI_V2_WETH_SPELL_3000_WETH_TO_SPELL: IPair = { ...POOL_SUSHI_V2_WETH_SPELL_03, tokenIn: WETH, tokenOut: SPELL };
export const PAIR_SUSHI_V2_WETH_ARBY_3000_WETH_TO_ARBY: IPair = { ...POOL_SUSHI_V2_WETH_ARBY_03, tokenIn: WETH, tokenOut: ARBY };
export const PAIR_SUSHI_V2_WETH_USDT_3000_WETH_TO_USDT: IPair = { ...POOL_SUSHI_V2_WETH_USDT_03, tokenIn: WETH, tokenOut: USDT };
export const PAIR_SUSHI_V2_WETH_WBTC_3000_WETH_TO_WBTC: IPair = { ...POOL_SUSHI_V2_WETH_WBTC_03, tokenIn: WETH, tokenOut: WBTC };
export const PAIR_SUSHI_V2_WETH_ADOGE_3000_WETH_TO_ADOGE: IPair = { ...POOL_SUSHI_V2_WETH_ADOGE_03, tokenIn: WETH, tokenOut: ADOGE };
export const PAIR_SUSHI_V2_WETH_LIQD_3000_WETH_TO_LIQD: IPair = { ...POOL_SUSHI_V2_WETH_LIQD_03, tokenIn: WETH, tokenOut: LIQD };
export const PAIR_SUSHI_V2_WETH_MIM_3000_WETH_TO_MIM: IPair = { ...POOL_SUSHI_V2_WETH_MIM_03, tokenIn: WETH, tokenOut: MIM };
export const PAIR_SUSHI_V2_WETH_FLUID_3000_WETH_TO_FLUID: IPair = { ...POOL_SUSHI_V2_WETH_FLUID_03, tokenIn: WETH, tokenOut: FLUID };
export const PAIR_SUSHI_V2_WETH_EMAX_3000_WETH_TO_EMAX: IPair = { ...POOL_SUSHI_V2_WETH_EMAX_03, tokenIn: WETH, tokenOut: EMAX };
export const PAIR_SUSHI_V2_WETH_USDC_3000_WETH_TO_USDC: IPair = { ...POOL_SUSHI_V2_WETH_USDC_03, tokenIn: WETH, tokenOut: USDC };
export const PAIR_SUSHI_V2_WETH_JETH_3000_WETH_TO_JETH: IPair = { ...POOL_SUSHI_V2_WETH_JETH_03, tokenIn: WETH, tokenOut: JETH };
export const PAIR_SUSHI_V2_WETH_SUSHI_3000_WETH_TO_SUSHI: IPair = { ...POOL_SUSHI_V2_WETH_SUSHI_03, tokenIn: WETH, tokenOut: SUSHI };
export const PAIR_SUSHI_V2_WETH_PEPE_3000_WETH_TO_PEPE: IPair = { ...POOL_SUSHI_V2_WETH_PEPE_03, tokenIn: WETH, tokenOut: PEPE };
export const PAIR_SUSHI_V2_WETH_FLUX_3000_WETH_TO_FLUX: IPair = { ...POOL_SUSHI_V2_WETH_FLUX_03, tokenIn: WETH, tokenOut: FLUX };
export const PAIR_SUSHI_V2_WETH_OMNI_3000_WETH_TO_OMNI: IPair = { ...POOL_SUSHI_V2_WETH_OMNI_03, tokenIn: WETH, tokenOut: OMNI };
export const PAIR_SUSHI_V2_WETH_HWT_3000_WETH_TO_HWT: IPair = { ...POOL_SUSHI_V2_WETH_HWT_03, tokenIn: WETH, tokenOut: HWT };
export const PAIR_SUSHI_V2_WETH_GOHM_3000_WETH_TO_GOHM: IPair = { ...POOL_SUSHI_V2_WETH_GOHM_03, tokenIn: WETH, tokenOut: GOHM };
export const PAIR_SUSHI_V2_WETH_SHARBI_3000_WETH_TO_SHARBI: IPair = { ...POOL_SUSHI_V2_WETH_SHARBI_03, tokenIn: WETH, tokenOut: SHARBI };
export const PAIR_SUSHI_V2_WETH_LINK_3000_WETH_TO_LINK: IPair = { ...POOL_SUSHI_V2_WETH_LINK_03, tokenIn: WETH, tokenOut: LINK };
export const PAIR_SUSHI_V2_WETH_ARB_3000_WETH_TO_ARB: IPair = { ...POOL_SUSHI_V2_WETH_ARB_03, tokenIn: WETH, tokenOut: ARB };
export const PAIR_SUSHI_V2_WETH_DAI_3000_WETH_TO_DAI: IPair = { ...POOL_SUSHI_V2_WETH_DAI_03, tokenIn: WETH, tokenOut: DAI };
export const PAIR_SUSHI_V2_WETH_GMX_3000_WETH_TO_GMX: IPair = { ...POOL_SUSHI_V2_WETH_GMX_03, tokenIn: WETH, tokenOut: GMX };


// ======================================================================
// GROUPS
// ======================================================================

// ==================== ALL PAIRS: WETH → X (SUSHI V2) ====================

export const PAIRS_SUSHI_V2_WETH_OUT: IPair[] = [
  // HASH
  PAIR_SUSHI_V2_WETH_HASH_3000_WETH_TO_HASH,

  // // USDCE
  // PAIR_SUSHI_V2_WETH_USDCE_3000_WETH_TO_USDCE,
  //
  // // MAGIC
  // PAIR_SUSHI_V2_WETH_MAGIC_3000_WETH_TO_MAGIC,
  //
  // // DPX
  // PAIR_SUSHI_V2_WETH_DPX_3000_WETH_TO_DPX,
  //
  // // ARVAULT
  // PAIR_SUSHI_V2_WETH_ARVAULT_3000_WETH_TO_ARVAULT,
  //
  // // SPELL
  // PAIR_SUSHI_V2_WETH_SPELL_3000_WETH_TO_SPELL,
  //
  // // ARBY
  // PAIR_SUSHI_V2_WETH_ARBY_3000_WETH_TO_ARBY,
  //
  // // USDT
  // PAIR_SUSHI_V2_WETH_USDT_3000_WETH_TO_USDT,
  //
  // // WBTC
  // PAIR_SUSHI_V2_WETH_WBTC_3000_WETH_TO_WBTC,
  //
  // // ADOGE
  // PAIR_SUSHI_V2_WETH_ADOGE_3000_WETH_TO_ADOGE,
  //
  // // LIQD
  // PAIR_SUSHI_V2_WETH_LIQD_3000_WETH_TO_LIQD,
  //
  // // MIM
  // PAIR_SUSHI_V2_WETH_MIM_3000_WETH_TO_MIM,
  //
  // // FLUID
  // PAIR_SUSHI_V2_WETH_FLUID_3000_WETH_TO_FLUID,
  //
  // // EMAX
  // PAIR_SUSHI_V2_WETH_EMAX_3000_WETH_TO_EMAX,
  //
  // // USDC
  // PAIR_SUSHI_V2_WETH_USDC_3000_WETH_TO_USDC,
  //
  // // JETH
  // PAIR_SUSHI_V2_WETH_JETH_3000_WETH_TO_JETH,
  //
  // // SUSHI
  // PAIR_SUSHI_V2_WETH_SUSHI_3000_WETH_TO_SUSHI,
  //
  // // PEPE
  // PAIR_SUSHI_V2_WETH_PEPE_3000_WETH_TO_PEPE,
  //
  // // FLUX
  // PAIR_SUSHI_V2_WETH_FLUX_3000_WETH_TO_FLUX,
  //
  // // OMNI
  // PAIR_SUSHI_V2_WETH_OMNI_3000_WETH_TO_OMNI,
  //
  // // HWT
  // PAIR_SUSHI_V2_WETH_HWT_3000_WETH_TO_HWT,
  //
  // // GOHM
  // PAIR_SUSHI_V2_WETH_GOHM_3000_WETH_TO_GOHM,
  //
  // // SHARBI
  // PAIR_SUSHI_V2_WETH_SHARBI_3000_WETH_TO_SHARBI,
  //
  // // LINK
  // PAIR_SUSHI_V2_WETH_LINK_3000_WETH_TO_LINK,
  //
  // // ARB
  // PAIR_SUSHI_V2_WETH_ARB_3000_WETH_TO_ARB,
  //
  // // DAI
  // PAIR_SUSHI_V2_WETH_DAI_3000_WETH_TO_DAI,
  //
  // // GMX
  // PAIR_SUSHI_V2_WETH_GMX_3000_WETH_TO_GMX,
];
