import {
  POOL_UNISWAP_V3_ARB_WETH_005, POOL_UNISWAP_V3_ARB_WETH_03, POOL_UNISWAP_V3_ARB_WETH_1, POOL_UNISWAP_V3_DAI_WETH_005,
  POOL_UNISWAP_V3_DAI_WETH_03, POOL_UNISWAP_V3_DAI_WETH_1, POOL_UNISWAP_V3_GMX_WETH_03, POOL_UNISWAP_V3_GMX_WETH_1,
  POOL_UNISWAP_V3_LINK_WETH_005, POOL_UNISWAP_V3_LINK_WETH_03,
  POOL_UNISWAP_V3_PENDLE_WETH_005, POOL_UNISWAP_V3_PENDLE_WETH_03,
  POOL_UNISWAP_V3_PENDLE_WETH_1, POOL_UNISWAP_V3_RAIN_WETH_001,
  POOL_UNISWAP_V3_RAIN_WETH_1,
  POOL_UNISWAP_V3_USDC_ARB_005, POOL_UNISWAP_V3_USDC_ARB_03,
  POOL_UNISWAP_V3_USDC_WBTC_005,
  POOL_UNISWAP_V3_USDC_WBTC_03,
  POOL_UNISWAP_V3_USDC_WBTC_1, POOL_UNISWAP_V3_USDC_WETH_001, POOL_UNISWAP_V3_USDC_WETH_005,
  POOL_UNISWAP_V3_USDC_WETH_03, POOL_UNISWAP_V3_USDC_WETH_1,
  POOL_UNISWAP_V3_USDCE_WETH_005, POOL_UNISWAP_V3_USDCE_WETH_03, POOL_UNISWAP_V3_USDT_WETH_001,
  POOL_UNISWAP_V3_USDT_WETH_005, POOL_UNISWAP_V3_USDT_WETH_03, POOL_UNISWAP_V3_USDT_WETH_1,
  POOL_UNISWAP_V3_WBTC_WETH_001, POOL_UNISWAP_V3_WBTC_WETH_005, POOL_UNISWAP_V3_WBTC_WETH_03,
  POOL_UNISWAP_V3_WBTC_WETH_1, POOL_UNISWAP_V3_WSTETH_WETH_001, POOL_UNISWAP_V3_WSTETH_WETH_03
} from './poolsUniswapV3.stabs';
import {ARB, DAI, GMX, LINK, PENDLE, RAIN, USDC, USDCE, USDT, WBTC, WETH, WSTETH} from '../tokens.stabs';
import {IPair} from '../../state.types';

// ==================== PAIR: WETH → X ====================

// ---------- USDC / WETH ----------
export const PAIR_UNISWAP_V3_USDC_WETH_100_WETH_TO_USDC: IPair  = { ...POOL_UNISWAP_V3_USDC_WETH_001, tokenIn: WETH, tokenOut: USDC };
export const PAIR_UNISWAP_V3_USDC_WETH_500_WETH_TO_USDC: IPair  = { ...POOL_UNISWAP_V3_USDC_WETH_005, tokenIn: WETH, tokenOut: USDC };
export const PAIR_UNISWAP_V3_USDC_WETH_3000_WETH_TO_USDC: IPair  = { ...POOL_UNISWAP_V3_USDC_WETH_03, tokenIn: WETH, tokenOut: USDC };
export const PAIR_UNISWAP_V3_USDC_WETH_10000_WETH_TO_USDC: IPair  = { ...POOL_UNISWAP_V3_USDC_WETH_1, tokenIn: WETH, tokenOut: USDC };

// ---------- USDT / WETH ----------
export const PAIR_UNISWAP_V3_USDT_WETH_100_WETH_TO_USDT: IPair  = { ...POOL_UNISWAP_V3_USDT_WETH_001, tokenIn: WETH, tokenOut: USDT };
export const PAIR_UNISWAP_V3_USDT_WETH_500_WETH_TO_USDT: IPair  = { ...POOL_UNISWAP_V3_USDT_WETH_005, tokenIn: WETH, tokenOut: USDT };
export const PAIR_UNISWAP_V3_USDT_WETH_3000_WETH_TO_USDT: IPair  = { ...POOL_UNISWAP_V3_USDT_WETH_03, tokenIn: WETH, tokenOut: USDT };
export const PAIR_UNISWAP_V3_USDT_WETH_10000_WETH_TO_USDT: IPair  = { ...POOL_UNISWAP_V3_USDT_WETH_1, tokenIn: WETH, tokenOut: USDT };

// ---------- WBTC / WETH ----------
export const PAIR_UNISWAP_V3_WBTC_WETH_100_WETH_TO_WBTC: IPair  = { ...POOL_UNISWAP_V3_WBTC_WETH_001, tokenIn: WETH, tokenOut: WBTC };
export const PAIR_UNISWAP_V3_WBTC_WETH_500_WETH_TO_WBTC: IPair  = { ...POOL_UNISWAP_V3_WBTC_WETH_005, tokenIn: WETH, tokenOut: WBTC };
export const PAIR_UNISWAP_V3_WBTC_WETH_3000_WETH_TO_WBTC: IPair  = { ...POOL_UNISWAP_V3_WBTC_WETH_03, tokenIn: WETH, tokenOut: WBTC };
export const PAIR_UNISWAP_V3_WBTC_WETH_10000_WETH_TO_WBTC: IPair  = { ...POOL_UNISWAP_V3_WBTC_WETH_1, tokenIn: WETH, tokenOut: WBTC };

// ---------- ARB / WETH ----------
export const PAIR_UNISWAP_V3_ARB_WETH_500_WETH_TO_ARB: IPair  = { ...POOL_UNISWAP_V3_ARB_WETH_005, tokenIn: WETH, tokenOut: ARB };
export const PAIR_UNISWAP_V3_ARB_WETH_3000_WETH_TO_ARB: IPair  = { ...POOL_UNISWAP_V3_ARB_WETH_03, tokenIn: WETH, tokenOut: ARB };
export const PAIR_UNISWAP_V3_ARB_WETH_10000_WETH_TO_ARB: IPair  = { ...POOL_UNISWAP_V3_ARB_WETH_1, tokenIn: WETH, tokenOut: ARB };

// ---------- DAI / WETH ----------
export const PAIR_UNISWAP_V3_DAI_WETH_500_WETH_TO_DAI: IPair  = { ...POOL_UNISWAP_V3_DAI_WETH_005, tokenIn: WETH, tokenOut: DAI };
export const PAIR_UNISWAP_V3_DAI_WETH_3000_WETH_TO_DAI: IPair  = { ...POOL_UNISWAP_V3_DAI_WETH_03, tokenIn: WETH, tokenOut: DAI };
export const PAIR_UNISWAP_V3_DAI_WETH_10000_WETH_TO_DAI: IPair  = { ...POOL_UNISWAP_V3_DAI_WETH_1, tokenIn: WETH, tokenOut: DAI };

// ---------- GMX / WETH ----------
export const PAIR_UNISWAP_V3_GMX_WETH_3000_WETH_TO_GMX: IPair  = { ...POOL_UNISWAP_V3_GMX_WETH_03, tokenIn: WETH, tokenOut: GMX };
export const PAIR_UNISWAP_V3_GMX_WETH_10000_WETH_TO_GMX: IPair  = { ...POOL_UNISWAP_V3_GMX_WETH_1, tokenIn: WETH, tokenOut: GMX };

// ---------- LINK / WETH ----------
export const PAIR_UNISWAP_V3_LINK_WETH_500_WETH_TO_LINK: IPair  = { ...POOL_UNISWAP_V3_LINK_WETH_005, tokenIn: WETH, tokenOut: LINK };
export const PAIR_UNISWAP_V3_LINK_WETH_3000_WETH_TO_LINK: IPair  = { ...POOL_UNISWAP_V3_LINK_WETH_03, tokenIn: WETH, tokenOut: LINK };

// ---------- RAIN / WETH ----------
export const PAIR_UNISWAP_V3_RAIN_WETH_100_WETH_TO_RAIN: IPair  = { ...POOL_UNISWAP_V3_RAIN_WETH_001, tokenIn: WETH, tokenOut: RAIN };
export const PAIR_UNISWAP_V3_RAIN_WETH_10000_WETH_TO_RAIN: IPair  = { ...POOL_UNISWAP_V3_RAIN_WETH_1, tokenIn: WETH, tokenOut: RAIN };

// ---------- USDCE / WETH ----------
export const PAIR_UNISWAP_V3_USDCE_WETH_500_WETH_TO_USDCE: IPair  = { ...POOL_UNISWAP_V3_USDCE_WETH_005, tokenIn: WETH, tokenOut: USDCE };
export const PAIR_UNISWAP_V3_USDCE_WETH_3000_WETH_TO_USDCE: IPair  = { ...POOL_UNISWAP_V3_USDCE_WETH_03, tokenIn: WETH, tokenOut: USDCE };

// ---------- PENDLE / WETH ----------
export const PAIR_UNISWAP_V3_PENDLE_WETH_500_WETH_TO_PENDLE: IPair  = { ...POOL_UNISWAP_V3_PENDLE_WETH_005, tokenIn: WETH, tokenOut: PENDLE };
export const PAIR_UNISWAP_V3_PENDLE_WETH_3000_WETH_TO_PENDLE: IPair  = { ...POOL_UNISWAP_V3_PENDLE_WETH_03, tokenIn: WETH, tokenOut: PENDLE };
export const PAIR_UNISWAP_V3_PENDLE_WETH_10000_WETH_TO_PENDLE: IPair  = { ...POOL_UNISWAP_V3_PENDLE_WETH_1, tokenIn: WETH, tokenOut: PENDLE };

// ---------- WSTETH / WETH ----------
export const PAIR_UNISWAP_V3_WSTETH_WETH_100_WETH_TO_WSTETH: IPair  = { ...POOL_UNISWAP_V3_WSTETH_WETH_001, tokenIn: WETH, tokenOut: WSTETH };
export const PAIR_UNISWAP_V3_WSTETH_WETH_3000_WETH_TO_WSTETH: IPair  = { ...POOL_UNISWAP_V3_WSTETH_WETH_03, tokenIn: WETH, tokenOut: WSTETH };


// -------------------- PAIR: USDC → WBTC --------------------

export const PAIR_UNISWAP_V3_USDC_WBTC_500_USDC_TO_WBTC: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WBTC_005,
  tokenIn: USDC,
  tokenOut: WBTC,
};

export const PAIR_UNISWAP_V3_USDC_WBTC_3000_USDC_TO_WBTC: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WBTC_03,
  tokenIn: USDC,
  tokenOut: WBTC,
};

export const PAIR_UNISWAP_V3_USDC_WBTC_10000_USDC_TO_WBTC: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WBTC_1,
  tokenIn: USDC,
  tokenOut: WBTC,
};

// -------------------- PAIR: USDC → ARB --------------------

export const PAIR_UNISWAP_V3_USDC_ARB_500_USDC_TO_ARB: IPair  = {
  ...POOL_UNISWAP_V3_USDC_ARB_005,
  tokenIn: USDC,
  tokenOut: ARB,
};

export const PAIR_UNISWAP_V3_USDC_ARB_3000_USDC_TO_ARB: IPair  = {
  ...POOL_UNISWAP_V3_USDC_ARB_03,
  tokenIn: USDC,
  tokenOut: ARB,
};

// -------------------- PAIR: USDC → WETH --------------------

export const PAIR_UNISWAP_V3_USDC_WETH_100_USDC_TO_WETH: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WETH_001,
  tokenIn: USDC,
  tokenOut: WETH,
};

export const PAIR_UNISWAP_V3_USDC_WETH_500_USDC_TO_WETH: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WETH_005,
  tokenIn: USDC,
  tokenOut: WETH,
};

export const PAIR_UNISWAP_V3_USDC_WETH_3000_USDC_TO_WETH: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WETH_03,
  tokenIn: USDC,
  tokenOut: WETH,
};

export const PAIR_UNISWAP_V3_USDC_WETH_10000_USDC_TO_WETH: IPair  = {
  ...POOL_UNISWAP_V3_USDC_WETH_1,
  tokenIn: USDC,
  tokenOut: WETH,
};



// ==================== ALL PAIRS: WETH → X ====================

export const PAIRS_WETH_OUT: IPair[] = [
  // USDC
  PAIR_UNISWAP_V3_USDC_WETH_100_WETH_TO_USDC,
  PAIR_UNISWAP_V3_USDC_WETH_500_WETH_TO_USDC,
  PAIR_UNISWAP_V3_USDC_WETH_3000_WETH_TO_USDC,
  PAIR_UNISWAP_V3_USDC_WETH_10000_WETH_TO_USDC,

  // USDT
  PAIR_UNISWAP_V3_USDT_WETH_100_WETH_TO_USDT,
  PAIR_UNISWAP_V3_USDT_WETH_500_WETH_TO_USDT,
  PAIR_UNISWAP_V3_USDT_WETH_3000_WETH_TO_USDT,
  PAIR_UNISWAP_V3_USDT_WETH_10000_WETH_TO_USDT,

  // WBTC
  PAIR_UNISWAP_V3_WBTC_WETH_100_WETH_TO_WBTC,
  PAIR_UNISWAP_V3_WBTC_WETH_500_WETH_TO_WBTC,
  PAIR_UNISWAP_V3_WBTC_WETH_3000_WETH_TO_WBTC,
  PAIR_UNISWAP_V3_WBTC_WETH_10000_WETH_TO_WBTC,

  // ARB
  PAIR_UNISWAP_V3_ARB_WETH_500_WETH_TO_ARB,
  PAIR_UNISWAP_V3_ARB_WETH_3000_WETH_TO_ARB,
  PAIR_UNISWAP_V3_ARB_WETH_10000_WETH_TO_ARB,

  // DAI
  PAIR_UNISWAP_V3_DAI_WETH_500_WETH_TO_DAI,
  PAIR_UNISWAP_V3_DAI_WETH_3000_WETH_TO_DAI,
  PAIR_UNISWAP_V3_DAI_WETH_10000_WETH_TO_DAI,

  // GMX
  PAIR_UNISWAP_V3_GMX_WETH_3000_WETH_TO_GMX,
  PAIR_UNISWAP_V3_GMX_WETH_10000_WETH_TO_GMX,

  // LINK
  PAIR_UNISWAP_V3_LINK_WETH_500_WETH_TO_LINK,
  PAIR_UNISWAP_V3_LINK_WETH_3000_WETH_TO_LINK,

  // RAIN
  PAIR_UNISWAP_V3_RAIN_WETH_100_WETH_TO_RAIN,
  PAIR_UNISWAP_V3_RAIN_WETH_10000_WETH_TO_RAIN,

  // USDCE
  PAIR_UNISWAP_V3_USDCE_WETH_500_WETH_TO_USDCE,
  PAIR_UNISWAP_V3_USDCE_WETH_3000_WETH_TO_USDCE,

  // PENDLE
  PAIR_UNISWAP_V3_PENDLE_WETH_500_WETH_TO_PENDLE,
  PAIR_UNISWAP_V3_PENDLE_WETH_3000_WETH_TO_PENDLE,
  PAIR_UNISWAP_V3_PENDLE_WETH_10000_WETH_TO_PENDLE,

  // WSTETH
  PAIR_UNISWAP_V3_WSTETH_WETH_100_WETH_TO_WSTETH,
  PAIR_UNISWAP_V3_WSTETH_WETH_3000_WETH_TO_WSTETH,
];

// ==================== ALL PAIRS: USDC → X ====================

export const PAIRS_USDC_OUT: IPair[] = [
  // WBTC
  PAIR_UNISWAP_V3_USDC_WBTC_500_USDC_TO_WBTC,
  PAIR_UNISWAP_V3_USDC_WBTC_3000_USDC_TO_WBTC,
  PAIR_UNISWAP_V3_USDC_WBTC_10000_USDC_TO_WBTC,

  // ARB
  PAIR_UNISWAP_V3_USDC_ARB_500_USDC_TO_ARB,
  PAIR_UNISWAP_V3_USDC_ARB_3000_USDC_TO_ARB,

  // WETH
  PAIR_UNISWAP_V3_USDC_WETH_100_USDC_TO_WETH,
  PAIR_UNISWAP_V3_USDC_WETH_500_USDC_TO_WETH,
  PAIR_UNISWAP_V3_USDC_WETH_3000_USDC_TO_WETH,
  PAIR_UNISWAP_V3_USDC_WETH_10000_USDC_TO_WETH,
];
