services:
  arbi-server-bots:
    container_name: arbi-server-bots
    build:
      context: .
      dockerfile: ./docker/DockerfileBackend
    ports:
      - "1001:3000"
    env_file:
      - .env
    restart: unless-stopped

#  arbi-second-server-bots:
#    container_name: arbi-second-server-bots
#    build:
#      context: .
#      dockerfile: ./docker/DockerfileBackend
#    ports:
#      - "1002:3000"
#    restart: unless-stopped
  arbi-second-server-bots:
    container_name: arbi-second-server-bots
    build:
      context: .
      dockerfile: ./docker/DockerfileBackend
    ports:
      - "1003:3000"
    restart: unless-stopped