// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ArbErrors$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ArbErrors";
  readonly sourceName: "contracts/ArbErrors.sol";
  readonly abi: [{"inputs":[],"name":"NO_ACTIVE_ALGEBRA_SWAP","type":"error"},{"inputs":[],"name":"NO_ACTIVE_V3_SWAP","type":"error"},{"inputs":[],"name":"PATH_TOO_SHORT","type":"error"},{"inputs":[],"name":"POOL_ZERO","type":"error"},{"inputs":[],"name":"ROUTER_ZERO","type":"error"},{"inputs":[],"name":"SLIPPAGE","type":"error"},{"inputs":[],"name":"TOKEN_NOT_IN_POOL","type":"error"},{"inputs":[],"name":"UNEXPECTED_ALGEBRA_POOL","type":"error"},{"inputs":[],"name":"UNEXPECTED_V3_POOL","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220c57614004dd14681e627bbd7dec4e00deeff16d2f5267a206a58ecffd079d69464736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220c57614004dd14681e627bbd7dec4e00deeff16d2f5267a206a58ecffd079d69464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ArbErrors.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ArbErrors"]: ArbErrors$Type;
    ["contracts/ArbErrors.sol:ArbErrors"]: ArbErrors$Type;
  }
}