// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IV3PoolLike$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IV3PoolLike";
  readonly sourceName: "contracts/V3SwapLib.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"bool","name":"zeroForOne","type":"bool"},{"internalType":"int256","name":"amountSpecified","type":"int256"},{"internalType":"uint160","name":"sqrtPriceLimitX96","type":"uint160"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"swap","outputs":[{"internalType":"int256","name":"amount0","type":"int256"},{"internalType":"int256","name":"amount1","type":"int256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"token0","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"token1","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/V3SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

export interface V3SwapLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "V3SwapLib";
  readonly sourceName: "contracts/V3SwapLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212201d1f1ac1fe89c9c79e9958f97600641afd9551a9b9c3e327afb4e85bc1e136a364736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212201d1f1ac1fe89c9c79e9958f97600641afd9551a9b9c3e327afb4e85bc1e136a364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/V3SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IV3PoolLike"]: IV3PoolLike$Type
    ["V3SwapLib"]: V3SwapLib$Type;
    ["contracts/V3SwapLib.sol:IV3PoolLike"]: IV3PoolLike$Type
    ["contracts/V3SwapLib.sol:V3SwapLib"]: V3SwapLib$Type;
  }
}