// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface AlgebraSwapLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "AlgebraSwapLib";
  readonly sourceName: "contracts/AlgebraSwapLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220deb79f9749802b2eafc907b625f9e941343fa7c1ca4677bf394ad465ff261ec664736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220deb79f9749802b2eafc907b625f9e941343fa7c1ca4677bf394ad465ff261ec664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/AlgebraSwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

export interface IAlgebraPool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAlgebraPool";
  readonly sourceName: "contracts/AlgebraSwapLib.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"bool","name":"zeroToOne","type":"bool"},{"internalType":"int256","name":"amountSpecified","type":"int256"},{"internalType":"uint160","name":"limitSqrtPrice","type":"uint160"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"swap","outputs":[{"internalType":"int256","name":"amount0","type":"int256"},{"internalType":"int256","name":"amount1","type":"int256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"token0","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"token1","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/AlgebraSwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["AlgebraSwapLib"]: AlgebraSwapLib$Type
    ["IAlgebraPool"]: IAlgebraPool$Type;
    ["contracts/AlgebraSwapLib.sol:AlgebraSwapLib"]: AlgebraSwapLib$Type
    ["contracts/AlgebraSwapLib.sol:IAlgebraPool"]: IAlgebraPool$Type;
  }
}