// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CamelotV2SwapLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CamelotV2SwapLib";
  readonly sourceName: "contracts/CamelotV2SwapLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122070f20d0d028711b23e00c9a84a792ab710dca8abae1fa4ae7f327d87c0f4be7164736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122070f20d0d028711b23e00c9a84a792ab710dca8abae1fa4ae7f327d87c0f4be7164736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/CamelotV2SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

export interface ICamelotV2Router$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICamelotV2Router";
  readonly sourceName: "contracts/CamelotV2SwapLib.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"amountIn","type":"uint256"},{"internalType":"uint256","name":"amountOutMin","type":"uint256"},{"internalType":"address[]","name":"path","type":"address[]"},{"internalType":"address","name":"to","type":"address"},{"internalType":"address","name":"referrer","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"}],"name":"swapExactTokensForTokensSupportingFeeOnTransferTokens","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/CamelotV2SwapLib.sol";
  readonly buildInfoId: "solc-0_8_28-a952fd7f856c40be8b8a3761b53df823bf5588f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CamelotV2SwapLib"]: CamelotV2SwapLib$Type
    ["ICamelotV2Router"]: ICamelotV2Router$Type;
    ["contracts/CamelotV2SwapLib.sol:CamelotV2SwapLib"]: CamelotV2SwapLib$Type
    ["contracts/CamelotV2SwapLib.sol:ICamelotV2Router"]: ICamelotV2Router$Type;
  }
}