import {ApiEndpointDto} from '../dto/api-endpoint.dto';

export const ApiStabs: ApiEndpointDto[] = [
  {
    method: 'GET',
    path: '/info/apis',
    description: 'Info about APIs. Response: [{method: string; path: string; description: string; tags: string[]; version: string; }]',
    tags: ['info', 'api'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/info',
    description: 'Server info. Response: { appVersion: string; serverStartedAt: string; botsCount: number; }',
    tags: ['info'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/info/bots-types-list',
    description: 'Bots types list. Response: [{ type: string; description: string; }]',
    tags: ['bot'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: 'info/job-type-list',
    description: 'Job types  list. Response: [{ type: string; description: string; }]',
    tags: ['job'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/store',
    description: 'Get current store snapshot. DOES_T WORK',
    tags: ['store', 'bot', 'job', 'info'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/bots/get-all',
    description: 'Get all launched bots. Response: [{ id: string; running: boolean; createdAt: string; jobCount: number; errorCount: number; lastJobTimeStart: string; lastJobTimeFinish: string; lastLatency: number; lastJobResult: { ok: boolean; latencyMs: number; result: { quoteExactInputSingle: { amountOut: string; sqrtPriceX96After: string; initializedTicksCrossed: string; gasEstimate: string; }; quoteExactOutputSingle: { amountIn: string; sqrtPriceX96After: string; initializedTicksCrossed: string; gasEstimate: string; }; }; blockNumber: number; }; }]',
    tags: ['bot'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/bot/:botId/params',
    description: 'Get bot params by botId.  Response: { id: string; running: boolean; createdAt: string; jobCount: number; errorCount: number; lastJobTimeStart: string; lastJobTimeFinish: string; lastLatency: number; lastJobResult: { ok: boolean; latencyMs: number; result: { quoteExactInputSingle: { amountOut: string; sqrtPriceX96After: string; initializedTicksCrossed: string; gasEstimate: string; }; quoteExactOutputSingle: { amountIn: string; sqrtPriceX96After: string; initializedTicksCrossed: string; gasEstimate: string; }; }; blockNumber: number; }; }',
    tags: ['bot'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/bot/:botId/settings',
    description: 'Get settings by botId. DOES_T WORK',
    tags: ['bot'],
    version: 'v1',
  },
  {
    method: 'PUT',
    path: '/bot/:botId/settings',
    description: 'Set settings by botId. Request: { id: string; botParams: IBotParams; actionParams: IActionParams; }. Response: { id: string; botParams: IBotParams; actionParams: IActionParams; }',
    tags: ['quotes', 'markets'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/api/quotes/html/getLastQuotesByMarketIdAndQuoteId/:marketId/:quoteId',
    description: 'Get last quotes by market ID and quote ID',
    tags: ['quotes', 'markets'],
    version: 'v1',
  },
  {
    method: 'POST',
    path: '/bot/${botId}/pause',
    description: 'Pause/resume execution of a bot rule. Request: {pause: bool}. Response: { id: botId, paused: pause }',
    tags: ['bot', 'pause'],
    version: 'v1',
  },
  {
    method: 'POST',
    path: '/bot/${botId}/restart',
    description: 'Restart bot execution. Immediately schedules a restart: the current job cycle finishes its iteration, state resets, and a new execution loop starts automatically. Response: { id: botId, restarted: true }',
    tags: ['bot', 'restart'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/rules/get-all',
    description: 'Get all bot rules. Response: [{ id: string; botParams: any;  jobParams: any}]',
    tags: ['rule'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/bot/:botId/errors',
    description: 'Get bot errors by botId. Response: [{createdAt: string; errorCode: string; message: string; details?: any; durationMs?: number | null; source?: string;}]',
    tags: ['bot', 'error'],
    version: 'v1',
  },
  {
    method: 'GET',
    path: '/bot/:botId/arbitrage',
    description: 'Get bot arbitrage by botId. Response: { createdAt: string; details: any}[]',
    tags: ['bot', 'arbitrage'],
    version: 'v1',
  },
];
